name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: eu-north-1
      #AWS_ACCOUNT_ID: 052368238934
      BACKEND_REPO: docker-demo/backend
      FRONTEND_REPO: docker-demo/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin \
          052368238934.dkr.ecr.$AWS_REGION.amazonaws.com

      # =====================
      # BUILD BACKEND
      # =====================

      - name: Build Backend
        run: |
          docker build -t $BACKEND_REPO:$COMMIT_SHA ./backend
          docker tag $BACKEND_REPO:$COMMIT_SHA \
          052368238934.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:$COMMIT_SHA

      - name: Push Backend
        run: |
          docker push \
          052368238934.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:$COMMIT_SHA

      # =====================
      # BUILD FRONTEND
      # =====================

      - name: Build Frontend
        run: |
          docker build -t $FRONTEND_REPO:$COMMIT_SHA ./frontend
          docker tag $FRONTEND_REPO:$COMMIT_SHA \
          052368238934.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:$COMMIT_SHA

      - name: Push Frontend
        run: |
          docker push \
          052368238934.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:$COMMIT_SHA

      # =====================
      # DEPLOY TO EKS
      # =====================

      - name: Deploy to EKS
        run: |
          sed -i "s|IMAGE_TAG|$COMMIT_SHA|g" k8s/*.yaml
          kubectl apply -f k8s/