name: CI-CD-Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 052368238934.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Backend
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker build -t backend:$COMMIT_SHA ./backend
          docker tag backend:$COMMIT_SHA <ECR_URI>/backend:$COMMIT_SHA

      - name: Build Frontend
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker build -t frontend:$COMMIT_SHA ./frontend
          docker tag frontend:$COMMIT_SHA <ECR_URI>/frontend:$COMMIT_SHA
        
      - name: Push Image
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)

          docker push 052368238934.dkr.ecr.eu-north-1.amazonaws.com/docker-demo:$COMMIT_SHA

      - name: Deploy to EKS
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)

          sed -i "s|IMAGE_TAG|$COMMIT_SHA|g" k8s/*.yaml

          kubectl apply -f k8s/
          
         

